Repository UMC-8th-kkukmoa/back-end, pull requests merged in 2025-08, with the labels that each got.

#60 [FEAT][junyong]: 다양한 요청에 대한 파싱 예외 처리
  src/main/java/kkukmoa/kkukmoa/apiPayload/exception/ExceptionAdvice.java
Labels: ✨Feat

#67 [CHORE] 프론트 연동 위한 설정 수정
  .github/workflows/deploy_dev.yml
  .github/workflows/deploy_prod.yml
  src/main/java/kkukmoa/kkukmoa/config/SwaggerConfig.java
  src/main/java/kkukmoa/kkukmoa/user/service/UserCommandService.java
  src/main/resources/application.yml
Labels: ⚙️Chore

#98 [Refactor][Federico] : Store 엔터티 및 입점신청 API 리팩토링
  src/main/java/kkukmoa/kkukmoa/admin/AdminController.java
  src/main/java/kkukmoa/kkukmoa/admin/service/StoreApprovalService.java
  src/main/java/kkukmoa/kkukmoa/admin/service/StoreRegistrationApprovalService.java
  src/main/java/kkukmoa/kkukmoa/apiPayload/code/status/ErrorStatus.java
  src/main/java/kkukmoa/kkukmoa/owner/controller/OwnerAuthController.java
  src/main/java/kkukmoa/kkukmoa/owner/controller/OwnerRegisterCheckController.java
  src/main/java/kkukmoa/kkukmoa/owner/dto/OwnerRegisterResponse.java
  src/main/java/kkukmoa/kkukmoa/owner/service/OwnerRegisterCheckService.java
  src/main/java/kkukmoa/kkukmoa/owner/service/OwnerRegisterService.java
  src/main/java/kkukmoa/kkukmoa/store/domain/Store.java
  src/main/java/kkukmoa/kkukmoa/store/domain/StoreRegistration.java
  src/main/java/kkukmoa/kkukmoa/store/enums/StoreStatus.java
  src/main/java/kkukmoa/kkukmoa/store/repository/StoreRegistrationRepository.java
  src/main/java/kkukmoa/kkukmoa/store/repository/StoreRepository.java
Labels: ♻️Refactor

#104 리뷰 관련 API 구현
  src/main/java/kkukmoa/kkukmoa/apiPayload/code/status/ErrorStatus.java
  src/main/java/kkukmoa/kkukmoa/apiPayload/exception/handler/ReviewHandler.java
  src/main/java/kkukmoa/kkukmoa/common/util/s3/controller/S3ImageController.java
  src/main/java/kkukmoa/kkukmoa/review/controller/ReviewController.java
  src/main/java/kkukmoa/kkukmoa/review/domain/Review.java
  src/main/java/kkukmoa/kkukmoa/review/domain/ReviewImage.java
  src/main/java/kkukmoa/kkukmoa/review/dto/CreateReviewResponse.java
  src/main/java/kkukmoa/kkukmoa/review/dto/CursorPage.java
  src/main/java/kkukmoa/kkukmoa/review/dto/ReviewCardDto.java
  src/main/java/kkukmoa/kkukmoa/review/dto/ReviewSummaryDto.java
  src/main/java/kkukmoa/kkukmoa/review/repository/ReviewCursorRepository.java
  src/main/java/kkukmoa/kkukmoa/review/repository/ReviewRepository.java
  src/main/java/kkukmoa/kkukmoa/review/repository/ReviewRepositoryImpl.java
  src/main/java/kkukmoa/kkukmoa/review/service/PreviewService.java
  src/main/java/kkukmoa/kkukmoa/review/service/ReviewCommandService.java
  src/main/java/kkukmoa/kkukmoa/review/service/ReviewCursorService.java
  src/main/java/kkukmoa/kkukmoa/review/service/ReviewQueryService.java
  src/main/java/kkukmoa/kkukmoa/review/util/CursorCodec.java
Labels: ✨Feat

#115 [REFACTOR][junyong]: 웹소켓 인증 수정
  src/main/java/kkukmoa/kkukmoa/apiPayload/code/status/ErrorStatus.java
  src/main/java/kkukmoa/kkukmoa/config/security/JwtTokenProvider.java
  src/main/java/kkukmoa/kkukmoa/config/websocket/JwtHandshakeInterceptor.java
  src/main/java/kkukmoa/kkukmoa/config/websocket/handler/QrWebSocketHandler.java
Labels: 🐛Bug, ♻️Refactor

#127 [Feat][Federico] : 관리자 입점신청 조회 API 및 리팩토링
  src/main/java/kkukmoa/kkukmoa/admin/AdminController.java
  src/main/java/kkukmoa/kkukmoa/admin/controller/AdminController.java
  src/main/java/kkukmoa/kkukmoa/admin/dto/PageDto.java
  src/main/java/kkukmoa/kkukmoa/admin/dto/PendingStoreSummary.java
  src/main/java/kkukmoa/kkukmoa/admin/service/AdminCommandService.java
  src/main/java/kkukmoa/kkukmoa/admin/service/AdminQueryService.java
  src/main/java/kkukmoa/kkukmoa/apiPayload/code/status/ErrorStatus.java
  src/main/java/kkukmoa/kkukmoa/apiPayload/exception/handler/AdminHandler.java
  src/main/java/kkukmoa/kkukmoa/config/security/JwtAuthenticationFilter.java
  src/main/java/kkukmoa/kkukmoa/config/security/JwtTokenProvider.java
  src/main/java/kkukmoa/kkukmoa/owner/controller/OwnerAuthController.java
  src/main/java/kkukmoa/kkukmoa/owner/controller/OwnerRegisterCheckController.java
  src/main/java/kkukmoa/kkukmoa/owner/dto/OwnerRegisterResponse.java
  src/main/java/kkukmoa/kkukmoa/owner/dto/request/OwnerLoginRequest.java
  src/main/java/kkukmoa/kkukmoa/owner/dto/request/OwnerRegisterRequest.java
  src/main/java/kkukmoa/kkukmoa/owner/dto/request/OwnerSignupRequest.java
  src/main/java/kkukmoa/kkukmoa/owner/dto/response/OwnerRegisterCheckResponse.java
  src/main/java/kkukmoa/kkukmoa/owner/dto/response/OwnerRegisterResponse.java
  src/main/java/kkukmoa/kkukmoa/owner/service/OwnerAccountService.java
  src/main/java/kkukmoa/kkukmoa/owner/service/OwnerCommandService.java
  src/main/java/kkukmoa/kkukmoa/owner/service/OwnerQueryService.java
  src/main/java/kkukmoa/kkukmoa/owner/service/OwnerRegisterCheckService.java
  src/main/java/kkukmoa/kkukmoa/owner/service/OwnerRegisterService.java
  src/main/java/kkukmoa/kkukmoa/review/controller/ReviewController.java
  src/main/java/kkukmoa/kkukmoa/review/converter/ReviewConverter.java
  src/main/java/kkukmoa/kkukmoa/review/dto/request/CreateReviewResponse.java
  src/main/java/kkukmoa/kkukmoa/review/dto/response/CursorPage.java
  src/main/java/kkukmoa/kkukmoa/review/dto/response/ReviewCardDto.java
  src/main/java/kkukmoa/kkukmoa/review/dto/response/ReviewCursorResponse.java
  src/main/java/kkukmoa/kkukmoa/review/dto/response/ReviewHeaderDto.java
  src/main/java/kkukmoa/kkukmoa/review/dto/response/ReviewSummaryDto.java
  src/main/java/kkukmoa/kkukmoa/review/service/PreviewService.java
  src/main/java/kkukmoa/kkukmoa/review/service/ReviewCommandService.java
  src/main/java/kkukmoa/kkukmoa/review/service/ReviewCursorService.java
  src/main/java/kkukmoa/kkukmoa/review/service/ReviewQueryService.java
  src/main/java/kkukmoa/kkukmoa/store/converter/StoreConverter.java
  src/main/java/kkukmoa/kkukmoa/store/repository/StoreRepository.java
  src/main/java/kkukmoa/kkukmoa/user/domain/User.java
Labels: ✨Feat, ♻️Refactor

#151 [REFACTOR][junyong]: 불필요 API 제거
  src/main/java/kkukmoa/kkukmoa/admin/controller/AdminController.java
  src/main/java/kkukmoa/kkukmoa/common/util/s3/controller/S3ImageController.java
  src/main/java/kkukmoa/kkukmoa/owner/controller/OwnerController.java
  src/main/java/kkukmoa/kkukmoa/store/controller/StoreController.java
Labels: ♻️Refactor

#157 dev -> main
  src/main/java/kkukmoa/kkukmoa/config/security/JwtAuthenticationFilter.java
  src/main/java/kkukmoa/kkukmoa/owner/controller/OwnerRegisterCheckController.java
  src/main/java/kkukmoa/kkukmoa/owner/dto/OwnerQrResponseDto.java
  src/main/java/kkukmoa/kkukmoa/owner/service/OwnerQueryService.java
Labels: ✨Feat
